# Python Block Course
# Assignment 1: Python basics (primitive data types and lists)

Marc Luettecke, Anna Bahss

Winter Term 2020 / 2021

In this first assignment we will practice how to use Jupyter Notebooks and how to execute Python code. You can score up to 3 points in this assignment. Please submit your solutions by sending it to **marc.luettecke@subsequent.ai** or **anna.bahss@uni-konstanz.de** (ideally both). Please include "**Python Blockkurs 2020 Assignment 1**" in the subject line of the email. The deadline for submission is on **Tuesday, October 27, 09:59**, everything submitted after will automatically receive a grade of 0/3.

**Notice: There's nothing new under the sun. Some of these problems are inspired by problems already existing out there. We can't avoid you copying code off the web, but know that 1. it is surprisingly easy to spot, if somebody uses techniques not introduced or referenced in the assignments yet, 2. you are missing out on actually understanding how to solve the problems with the tools (or at least hints) provided. Do yourself a favor and don't plagiarize.**

## 1.1 Working with lists
Lists are one of the most prominent data structures in programming in general. In this exercise, we will use basic operations to slice entries of a list and subset a list according to a logical condition. You will encounter some basic functionality, which DataCamp has not covered, but the Python documentation or Stackoverflow allow for comprehensive introductions to most programming problems (programming is maybe 30% *knowing* and 70% *knowing where to find*). Let's get started!

<div class="alert alert-block alert-info">
<b>Exercise (1.5 Points)</b>: Work through the documented steps below and solve the assignment. Be careful for hints and specific instructions.
</div>

In [1]:
# define the list to work with for the odd integers from 1-99 (including 99 - careful!), use the range() function for that and call the list 'integer_list' - important: the range function does not return a list Object out of the box, but you need to convert the range-iterator to a list after callign the range function! Important: the range() function starts like all Python indices at 0 not 1 as f. ex. R.

# Print the result


**Aside 1:** 

How to research how a specific function works? You can google it, research on the official documentation sites or dive into YouTube videos. Be sure to check out the "A helping Hand" section in the introduction document enclosed in the first e-mail we sent you. 

**Either way, especially as long as you are learning, but even beyond that, do not just blindly copy code. Try to understand what it's doing, so you can re-apply it to another problem afterwards.**

**Aside 2:**

**For-loop:**

A common mechanism in programming to iterator over a bunch of entries (here, our list entries). We will dive deeper into this concept on day 2, but for now just use the syntax:
    
`
for entry in list:
    'do something with entry'
`


Here the 'entry' is a name that we have chosen and the 'do something' represents a code that you can do with every element (named entry) of that list.

**If-statement:** 

You have already encountered logical statements in the DataCamp class. Now we want to use these more programmatically. If you have ever used Excel, this part is the same as the 'if-else' statements in Excel.

`
if condition:
    'do something'
else:
    'do something else'
`

With these building blocks, you should be able to subset the list now, **by iterating over its elements and appending every element to a new list if it meets the condition within the quotation marks**.



Now we will subset the list to only the elements that are (strictly) larger than 30, use a for-loop and an if statement for that

In [30]:
# build a new empty list for the entries meeting the condition, which we will populate within the loop and call it subset_integers

import random
subset_integers = []
# define the for loop over all the entries in the list

# I do not see any sample list here, does it mean that I need to create it by myself or I miss something?
sample_integers = [random.randint(1, 100) for i in range(20)]
for i in sample_integers:

    # define the if condition and append (see the list method '.append()') the entries that meet the requirement to be larger than 30
    if i > 30:
        subset_integers.append(i)
    # we do not need an else condition, because the loop automatically continues if the 'if-condition' is not met. In more specific cases you could also write "else: continue"

    
# print the new list

print(subset_integers)

[40, 70, 100, 76, 39, 51, 40, 37, 65, 78, 48, 50, 66, 52, 100]


Let's combine the new techniques we have learned to a more challenging example:

Build a list of lists **(2D)** and call it list_2d. The first dimension is of **length 10**, the second dimension is of **increasing length of all the integers from 0 to the index of the first dimension, exclude an empty list as an entry**. So, as an example, the corresponding list of lists for length 3 would look like:

`[[0],
 [0, 1],
 [0, 1, 2]]`

In [6]:
#Use a for loop and the range iterator to solve the problem.
list_2d = []
for i in range(10):
    temp_list = []
    for j in range(i+1):
        temp_list.append(j)
    list_2d.append(temp_list)

# print your list
print(list_2d)

# double check the length (=10) of the list with the len() function
print(len(list_2d))


[[0], [0, 1], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5, 6], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7, 8], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]
10


Build a christmas tree. Print the following output to the console with the techniques you have learned so far (loop through the tree height):

In [5]:
#       *    
#      ***   
#     *****  
#    ******* 
#   *********

Hint:
1. Text in python is called 'strings'. As you have learned, you can print multiple occurences of a string by 'multiplying' it, so try: print('hello' * 3)
2. Try to find the pattern of empty spaces in the tree (' ' is an empty string) to the tree height (here 5). A lot of programming, especially efficient programming is to utilize mathematical patterns in numbers, this exercise practices this approach.
3. Use the common '+' operator in Python to combine two strings, so to print the top row by hand, we can use:

In [22]:
# define the tree height to a variable called 'tree_height'
tree_height = 10

# loop over the tree height to build the tree iteratively. If done right, you can change the tree_height variable to any value you want and still get a symmetric tree.
for i in range(tree_height):
    mul_mid = 2*(i+1)-1
    mul_side = (2*(tree_height)+6 - 2*(i+1)-1)//2
    print('#'+' '*mul_side+'*'*mul_mid+' '*mul_side)


#           *           
#          ***          
#         *****         
#        *******        
#       *********       
#      ***********      
#     *************     
#    ***************    
#   *****************   
#  *******************  


## 1.2 Working with numpy
Numpy is one of the  most important tools in a data scientist's toolbox with Python. It introduces a new data structure, the numpy array, which behaves a lot like a list, but allows for vectorized (read here: much faster) operations and a bunch of methods right out the box. Anaconda comes with numpy pre-installed, for plain Python environments, you might have to install it by hand.

<div class="alert alert-block alert-info">
<b>Exercise (1.5 Points)</b>: Work through the documented steps below and solve the assignment. Be careful for hints and specific instructions.
</div>

In [24]:
# import  numpy with its common shorthand 'np'
import numpy as np


In [31]:
# define the same list of integers (no subsetting just yet) as a numpy array, call it np_integers

# 'same list? same as ...my sample_integers?'
np_integers = np.array(sample_integers)


# print the np array
print(np_integers)


[ 22  40  27  70 100  76  39  17  51  40  37  65  27  78   4  48  50  66
  52 100]


We have seen how troublesome some easy subsetting for lists can become (and highly unperformant for large lists) accomplish the same subsetting with a logical condition in one line of numpy (like you have learned in the DataCamp course), call the resulting array subset_np

In [35]:
# subset the numpy array in one line
subset_integers = np.extract(np_integers>30, np_integers)
# print the resulting numpy array
print(subset_integers)


[ 40  70 100  76  39  51  40  37  65  78  48  50  66  52 100]


In [36]:
# subset them again to entries strictly larger than 50 in one line in numpy and multiply all the entries by 3. Call the new array 'subset_again_np'
subset_again_np = 3*np.extract(subset_integers>50, subset_integers)

# print the new subset also control the length to make sure the entries behave as expected
print(subset_again_np)

[210 300 228 153 195 234 198 156 300]


We have seen that numpy allows for some easier functionality than regular lists. Let's work with some functions that you might have not seen that make numpy a very versatile tool in your toolbox.

Let's say we have a list of numbers from 1-20 (inclusive) and would like to break them into groups of 2 and find their mean value per group. This would include a lot of slicing and looping with lists, but with numpy we can do better.

In [45]:
# create a list of numbers from 1-20 (inclusive), call it some meaningful variable (not just 'list')
some_meaningful_variable = [i for i in range(1, 21)]

# convert the list to a np array
some_meaningful_variable = np.array(some_meaningful_variable)

# build a 2 D array with 2 elements per array with the np.reshape() method, google its documentation to find specifics about the syntax - result example: 
#  [[1, 2]
#   [3, 4]
#    ...
#   [19, 20]]

meaningful_arrray_2D = some_meaningful_variable.reshape(-1, 2)
print(meaningful_arrray_2D)


# find the average per sub array and print it without a loop (hint: look up the np.mean() function and its keyword arguments)
# result example: [1.5 3.5 ... 19.5]
print(np.mean(meaningful_arrray_2D, axis=1))




[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[ 1.5  3.5  5.5  7.5  9.5 11.5 13.5 15.5 17.5 19.5]
